#disabled=yes
#images=yes
videos=yes
#audio=no
additional_image_exts=jfif,gif,webp,
additional_video_exts=mkv,webm,gif,m4v,mpeg,mov,mp4
#additional_audio_exts=list,of,ext
ignore_hidden=yes
same_type=yes
directory_mode=auto
ignore_patterns=^~,^bak-,%.bak$,^tar,^gz
