# Written by videoclip on Sun May 10 04:38:36 2026.
audio_bitrate=32k
font_size=24
osd_align=7
osd_outline=1.5
clean_filename=yes
litterbox=no
litterbox_expire=1h
sub_font=Noto Sans CJK JP
custom_upload_command=
filename_template=%n@%s-%e_%d
video_folder_path=/sto2
audio_folder_path=/sto2
video_quality=0
preset=slow
video_format=mp4
video_bitrate=10M
video_width=-2
video_height=-2
video_fps=60
audio_format=aac
