#!/bin/sh
# shellcheck disable=SC2155
# 4ndr0666
#                           # === ZPROFILE === #

# DEFAULT PATH
#export PATH="$PATH:$(find /home/git/clone/4ndr0666/scr -type d -not -path '*/.git/*' | \paste -sd ':' -):$HOME/.local/bin:/usr/bin:/usr/local/bin:/bin:/sbin:/usr/sbin:$HOME/.npm-global/bin:${XDG_DATA_HOME:-/home/andro/.local/share}/gem/ruby/3.4.5/bin:$XDG_DATA_HOME/virtualenv:$XDG_DATA_HOME/go/bin:${CARGO_HOME-:/home/andro/.local/share/cargo}/bin:/opt/depot_tools:${JAVA_HOME:-/usr/lib/jvm/default/bin}"

unsetopt PROMPT_SP 2>/dev/null

# PYTHON ENV VARIABLES (before static shims)
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export INPUTRC="$XDG_CONFIG_HOME/zsh/inputrc"
export PIP_DOWNLOAD_CACHE="$XDG_CACHE_HOME/pip/"
export VENV_HOME="$XDG_DATA_HOME/virtualenv"
export VIRTUAL_ENV_PROMPT="(💀)"
export PIPX_HOME="$XDG_DATA_HOME/pipx"
# Initialize
#eval "$(pyenv init --path)"
#pyenv init -

# Static dirs
PATH="/bin:/usr/bin:/sbin:/usr/sbin:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="/opt/amdgpu/bin:$PATH"
PATH="${CARGO_HOME:-$HOME/.local/share/cargo}/bin:$PATH"
PATH="${XDG_DATA_HOME:-/home/andro/.local/share}/go/bin:$PATH"
PATH="${XDG_DATA_HOME:-$HOME/.local/share}/virtualenv/venv/bin:$PATH"
PATH="$HOME/.npm-global/bin:$PATH"
PATH="${JAVA_HOME:-/usr/lib/jvm/default/bin}:$PATH"
PATH="${PIPX_HOME:-$XDG_DATA_HOME/pipx}/bin:$PATH"
PATH="${PYENV_ROOT:-$XDG_DATA_HOME/pyenv}/bin:$PATH"
PATH="$PYENV_ROOT/shims:$PATH"


#path=(
#  /usr/local/{s}bin
#  /usr/{s}bin
#  /bin
#  /sbin
#  "$HOME/.local/bin"
#  "${CARGO_HOME:-$HOME/.cargo}/bin"
#  "${XDG_DATA_HOME:-$HOME/.local/share}/go/bin"
#  "${XDG_DATA_HOME:-$HOME/.local/share}/virtualenv/bin"  # usually not needed
#  "${JAVA_HOME:-/usr/lib/jvm/default}/bin"
#  "$path[@]"
#)


# Dynamic Ruby path
gem_ruby_base_path="${XDG_DATA_HOME:-$HOME/.local/share}/gem/ruby"
if [ -d "$gem_ruby_base_path" ]; then
  latest_version_dir=$(ls -v "$gem_ruby_base_path" | tail -n 1)
  if [ -n "$latest_version_dir" ]; then
    PATH="${gem_ruby_base_path}/${latest_version_dir}/bin:$PATH"
  fi
fi

#if (( $+commands[ruby] )) && (( $+commands[gem] )); then
#  user_gem_bin="$(ruby -e 'puts Gem.user_dir')/bin"
#  if [[ -d "$user_gem_bin" ]]; then
#    path=("$user_gem_bin" $path)
#  fi
#fi
#
## Fallback for rare cases where Gem.user_dir not available or Ruby broken
#if [[ -d "${XDG_DATA_HOME:-$HOME/.local/share}/gem/ruby" ]]; then
#  latest_ver=$(ls -1v "${XDG_DATA_HOME:-$HOME/.local/share}/gem/ruby" | tail -n1)
#  [[ -n "$latest_ver" && -d "${XDG_DATA_HOME:-$HOME/.local/share}/gem/ruby/$latest_ver/bin" ]] && \
#    path=("${XDG_DATA_HOME:-$HOME/.local/share}/gem/ruby/$latest_ver/bin" $path)
#fi


# Cache file
cache_file="${XDG_CACHE_HOME:-$HOME/.cache}/dynamic_scr_dirs.list"
scr_root='/home/git/clone/4ndr0666/scr'
if [ -d "$scr_root" ]; then
  # Check if cache needs to be rebuilt (missing or scr_root is newer)
  if [ ! -f "$cache_file" ] || [ "$scr_root" -nt "$cache_file" ]; then
    # Call the function from .zshrc to rebuild and update PATH
    update_scr_path
  else
    # If cache is valid, just read it and update PATH
    if [ -r "$cache_file" ]; then
      local cached_dirs=$(tr '\n' ':' < "$cache_file" | sed 's/:$//')
      export PATH="$PATH:$cached_dirs"
    fi
  fi
fi
typeset -U PATH
export PATH


# DEFAULT PROGRAMS
export EDITOR="nvim"
export term="kitty"
export TERMINAL="kitty"
export TERMINAL_PROG="st"
export BROWSER="brave-beta"


# XDG SPECIFICATIONS
if [ -z "$XDG_RUNTIME_DIR" ]; then
    export XDG_RUNTIME_DIR="/run/user/$(id -u)"
fi
if [ ! -d "$XDG_RUNTIME_DIR" ]; then
    mkdir "$XDG_RUNTIME_DIR"
    \chmod 0700 "$XDG_RUNTIME_DIR"
fi
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XCURSOR_PATH="/usr/share/icons:$XDG_DATA_HOME/icons"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.

# Wine
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export WINEARCH="win32"


# Go
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
#export GOROOT="$(go env GOROOT 2>/dev/null || echo '/usr/lib/go')"


# Ruby
export GEM_HOME="$XDG_DATA_HOME/gem"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export RBENV_ROOT="$XDG_DATA_HOME/rbenv"


# Electron
export ELECTRON_CACHE="$XDG_CACHE_HOME/electron"
# export ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"


# Node
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export NODE_DATA_HOME="$XDG_DATA_HOME/node"
export NODE_CONFIG_HOME="$XDG_CONFIG_HOME/node"
#export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NVM_COLORS="cmgRY"


# ENVIRONMENT
export LD_LIBRARY_PATH="$XDG_DATA_HOME/lib:/usr/local/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export UNISON="$XDG_DATA_HOME/unison"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export DICS="/usr/share/stardict/dic/"
export W3M_DIR="$XDG_DATA_HOME/w3m"
export TLDR_CACHE_DIR="$XDG_CACHE_HOME/tldr"
export PARALLEL_HOME="$XDG_CONFIG_HOME/parallel"
#export SCREENRC="$XDG_CONFIG_HOME/screen/screenrc"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=\"$XDG_CONFIG_HOME/java\""
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
#export LIBVA_DRIVER_NAME=radeonsi
#export LIBVA_DISPLAY=wayland
export HISTFILE="$XDG_DATA_HOME/history"
export TRASHDIR="$XDG_DATA_HOME/Trash"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export AUR_DIR="$XDG_CACHE_HOME/yay/"


## My SQL
# export PSQL_HOME="$XDG_DATA_HOME/postgresql"
# export MYSQL_HOME="$XDG_DATA_HOME/mysql"
# export SQLITE_HOME="$XDG_DATA_HOME/sqlite"
# export SQL_DATA_HOME="$XDG_DATA_HOME/sql"
# export SQL_CONFIG_HOME="$XDG_CONFIG_HOME/sql"
# export SQL_CACHE_HOME="$XDG_CACHE_HOME/sql"
# mkdir -p "$PSQL_HOME" \
#    "$MYSQL_HOME" \
#    "$SQLITE_HOME" \
#    "$SQL_DATA_HOME" \
#    "$SQL_CONFIG_HOME" \
#    "$SQL_CACHE_HOME" >/dev/null 2>&1
# \chmod ug+rw "$PSQL_HOME" \
#    "$MYSQL_HOME" \
#    "$SQLITE_HOME" \
#    "$SQL_DATA_HOME" \
#    "$SQL_CONFIG_HOME" \
#    "$SQL_CACHE_HOME"


# Ensure directories
mkdir -p "$XDG_DATA_HOME/lib" \
    "$XDG_DATA_HOME/go/bin" \
    "$XDG_DATA_HOME/cargo/bin" \
    "$XDG_DATA_HOME/zsh" \
    "$XDG_CACHE_HOME/zsh" \
    "$XDG_DATA_HOME/node/npm-global" \
    "$WINEPREFIX" \
    "$CARGO_HOME" \
    "$GOPATH" \
    "$GOMODCACHE" \
    "$AUR_DIR" \
    "$PIPX_HOME" \
    "$VENV_HOME" \
    "$PIP_DOWNLOAD_CACHE" \
    "$RUSTUP_HOME" \
    "$RBENV_ROOT" \
    "$PARALLEL_HOME" \
    "$GEM_HOME" \
    "$W3M_DIR" \
    "$ELECTRON_CACHE" \
    "$NVM_CONFIG_HOME" \
    "$NODE_DATA_HOME" \
    "$NODE_CONFIG_HOME" >/dev/null 2>&1


# Ensure Permissions
[[ -f "$HISTFILE" ]] && chmod ug+rw "$HISTFILE"
\chmod ug+rw "$WINEPREFIX" \
    "$CARGO_HOME" \
    "$GOPATH" \
    "$GOMODCACHE" \
    "$AUR_DIR" \
    "$PIPX_HOME" \
    "$VENV_HOME" \
    "$RUSTUP_HOME" \
    "$RBENV_ROOT" \
    "$PARALLEL_HOME" \
    "$GEM_HOME" \
    "$W3M_DIR" \
    "$XDG_DATA_HOME/lib" \
    "$XDG_DATA_HOME/go/bin" \
    "$XDG_DATA_HOME/cargo/bin" \
    "$XDG_CONFIG_HOME/nvm" \
    "$XDG_CACHE_HOME/zsh" \
    "$XDG_DATA_HOME/virtualenv" \
    "$ELECTRON_CACHE" \
    "$NODE_DATA_HOME" \
    "$XDG_DATA_HOME/node/npm-global" >/dev/null 2>&1


# ASKPASS
export SUDO_ASKPASS="$XDG_CONFIG_HOME"/wayfire/scripts/rofi_askpass  # Wayland
#export SUDO_ASKPASS="/usr/bin/pinentry-dmenu"    # Xorg


# PAGER
export PAGER='less'
#export MANPAGER="sh -c 'if [ -t 1 ]; then col -bx | bat -l man -p; else col -bx | bat -l man -p --color=always --paging=always; fi | less -R'"
#export BAT_PAGER="less -R"
#export MANPAGER="sh -c 'col -bx | bat -l man -p | less -R'"
#export MANPAGER="sh -c 'col -bx | bat -l man -p --paging always'


# GPG
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
if [ ! -d "$GNUPGHOME" ]; then
    mkdir -p "$GNUPGHOME"
    \chmod 700 "$GNUPGHOME"
fi
#gpg_env_file="$ZDOTDIR/gpg_env"
#if [ -f "$gpg_env_file" ]; then
#    source "$gpg_env_file"
#else
#    echo "Warning: $gpg_env_file not found"
#fi


# X11 ENVIRONMENT ---
#export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
#export QT_STYLE_OVERRIDE='adwaita-dark'


# OPENBOX
# export XGD_CURRENT_DESKTOP='openbox'
# export _JAVA_AWT_WM_NONREPARENTING=1
# export OpenGL_GL_PREFERENCE=GLVND  # For screen tearing
# export QT_QPA_PLATFORMTHEME=qt5ct
# export MOZ_USE_XINPUT2=1
# export AWT_TOOLKIT=MToolkit wmname LG3D  # May have to install wmname
# export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.pla
#f.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel ${_JAVA_OPTIONS}"


# FZF; default search command:
export FZF_DEFAULT_COMMAND='fd --no-ignore --hidden --follow --exclude ".git"'

# === Config Testint ===
#export FZF_DEFAULT_OPTS="
#  --height=60%
#  --border=double
#  --padding=1%
#  --info=right
#  --separator=_
#  --preview='
#    set filename (basename {})
#    if string match -q \"*.txt\" -- \$filename
#      bat --style=numbers --color=always {}
#    else if string match -q \"*.pdf\" -- \$filename
#      zathura {} &
#    else if string match -q \"*.jpg\" -- \$filename
#      feh {} &
#    else if string match -q \"*.jpeg\" -- \$filename
#      feh {} &
#    else if string match -q \"*.png\" -- \$filename
#      feh {} &
#    else if string match -q \"*.gif\" -- \$filename
#      feh {} &
#    else
#      bat --style=numbers --color=always {}
#    end
#  '
#  --preview-window=hidden:right:69%
#  --preview-label=eyes
#  --margin=5%
#  --border-label=search
#  --color=fg:#005b69,fg+:#15FFFF,bg:#151515,bg+:#262626 \
#  --color=hl:#15FFFF,hl+:#15FFFF,info:#195761,marker:#15FFFF \
#  --color=prompt:#00f7ff,spinner:#64e290,pointer:#15FFFF,header:#07fff7 \
#  --color=border:#262626,preview-border:#15FFFF,label:#005b69,query:#15ffff \
#  --border-label='search' --prompt='≽  ' --marker='✔' --pointer='☞'
#  --layout=reverse
#  --prompt=💀
#  --bind='enter:execute(
#    set filename (basename {})
#    if string match -q \"*.txt\" -- \$filename
#      micro  {}
#    else if string match -q \"*.pdf\" -- \$filename
#      zathura {}
#    else if string match -q \"*.jpg\" -- \$filename
#      nsxiv {}
#    else if string match -q \"*.jpeg\" -- \$filename
#      nsxiv {}
#    else if string match -q \"*.png\" -- \$filename
#      nsxiv {}
#    else if string match -q \"*.gif\" -- \$filename
#      nsxiv {}
#    else
#      micro {}
#    end
#  )'
#  --bind=ctrl-p:toggle-preview
#"

## === Config 1 ===
#export FZF_DEFAULT_OPTS="
#  --layout=reverse
#  --prompt=💀
#  --border=thinblock
#  --height=40%
#  --padding=1%
#  --info=right
#  --tiebreak=index
#  --scrollbar='│'
#  --separator='_'
#  --preview='setopt NO_NOMATCH; set filename=\$(basename {}) ; case \$filename in
#    *.conf|*.py|*.sh|*.ini|*.txt|*.md) bat {} & ;;
#    *.pdf) zathura {} & ;;
#    *.jpg|*.jpeg|*.png|*.gif|*.webp|*.tiff|*.bmp|*.auto) nsxiv {} & ;;
#    *) file {} ;;
#esac'
#  --preview-window=hidden
#  --bind='ctrl-p:change-preview-window(right|69%|hidden)'
#  --preview-label=eyes
#  --margin=5%
#  --bind='ctrl-y:execute-silent(printf {} | cut -f 2- | wl-copy --trim-newline)'
#  --color=fg:#005b69,fg+:#15FFFF,bg:#151515,bg+:#262626 \
#  --color=hl:#15FFFF,hl+:#15FFFF,info:#195761,marker:#15FFFF \
#  --color=prompt:#00f7ff,spinner:#64e290,pointer:#15FFFF,header:#07fff7 \
#  --color=border:#262626,preview-border:#15FFFF,label:#005b69,query:#15ffff \
#  --border-label='search' --prompt='≽  ' --marker='✔' --pointer='☞'
#"

## === Config 1 ===
#--preview-window=up,1,border-horizontal

## === Config 2 ===
#--preview='file {}'
#--bind='ctrl-/:change-preview-window(50%|hidden|)' \

# === Config 3 ===
#--preview='bat --style=numbers --color=always {}'
#--preview-window=hidden:right:69%

# === Config 4 ===
export FZF_DEFAULT_OPTS="
  --height 60% --layout=reverse --border=thinblock --info=right --scrollbar='│'
  --prompt='≽  ' --pointer='☞' --marker='✔' --header-first
  --color fg:#a0f0f0,fg+:#15fafa,bg:#0a0f1a,bg+:#101827
  --color hl:#15fafa,hl+:#15fafa,prompt:#15adad,pointer:#15fafa
  --color border:#157d7d,preview-border:#15fafa,separator:#157d7d
  --preview-window='hidden:right:60%:wrap'
  --bind 'ctrl-p:change-preview-window(right|69%|hidden|)'
  --bind 'ctrl-y:execute-silent(printf {} | wl-copy --trim-newline || echo {} | xclip -sel clip)'
  --preview '
    file=\"\$(basename {})\"
    mime=\$(file -b --mime-type {})
    case \"\$file\" in
      *.sh|*.bash|*.zsh|*.py|*.conf|*.toml|*.yaml|*.yml|*.json|*.md|*.txt|*.ini)
        bat --color=always --style=changes,grid --terminal-width=\$(tput cols) {} 2>/dev/null ;;
      *.jpg|*.jpeg|*.png|*.gif|*.webp|*.svg)
        chafa --size=60x30 --animate=false {} 2>/dev/null || echo \"Image: \$(file -b {})\" ;;
      *.pdf)
        pdftotext -l 6 {} - 2>/dev/null | head -n 160 || echo \"PDF document\" ;;
      *)
        if [[ \$mime == image/* ]]; then
          chafa --size=60x30 {} 2>/dev/null || file -b {}
        else
          file -b --mime-type {}
        fi ;;
    esac'
"


# FZF Themes
# === 4ndr0hack Theme === #
#--color=fg:#005b69,fg+:#15FFFF,bg:#151515,bg+:#262626 \
#--color=hl:#15FFFF,hl+:#15FFFF,info:#195761,marker:#15FFFF \
#--color=prompt:#00f7ff,spinner:#64e290,pointer:#15FFFF,header:#07fff7 \
#--color=border:#262626,preview-border:#15FFFF,label:#005b69,query:#15ffff \
#--border-label-pos='-54' --prompt='≽  ' --marker='✔' --pointer='☞' --separator='-'"

# === Garuda Theme === #
#--height=40% --layout=reverse --info=inline --border --margin=1 --padding=1 \
#--tiebreak=index \
#--preview 'bat --color=always {}' --preview-window '~3' \
#--color 'bg+:-1,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8' \
#--color 'fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc' \
#--color 'marker:#f5e0dc,fg+:#a6e3a1,prompt:#cba6f7,hl+:#f38ba8'"

# === Dark Transparency Theme === #
# --color 'fg:#bbccdd,fg+:#ddeeff,bg:#334455,preview-bg:#223344,border:#778899"

## === Basic 16 ===
#--color=16

# Less
export LESS="R"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
# === Conf 3 ===
export LESS_TERMCAP_md=$'\e[01;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;44;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[01;32m'

## === Conf 1 ===
#export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
#export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
#export LESS_TERMCAP_me="$(printf '%b' '[0m')"
#export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
#export LESS_TERMCAP_se="$(printf '%b' '[0m')"
#export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
#export LESS_TERMCAP_ue="$(printf '%b' '[0m')"

## === Conf 2 ===
#export LESS_TERMCAP_mb="$(printf '%b' '')"
#export LESS_TERMCAP_md="$(printf '%b' '')"
#export LESS_TERMCAP_me="$(printf '%b' '')"
#export LESS_TERMCAP_so="$(printf '%b' '')"
#export LESS_TERMCAP_se="$(printf '%b' '')"
#export LESS_TERMCAP_us="$(printf '%b' '')"
#export LESS_TERMCAP_ue="$(printf '%b' '')"

# === Conf 4 === #
#export LESS_TERMCAP_mb=$(printf "\e[1;31m")
#export LESS_TERMCAP_md=$(printf "\e[1;31m")
#export LESS_TERMCAP_me=$(printf "\e[0m")
#export LESS_TERMCAP_se=$(printf "\e[0m")
#export LESS_TERMCAP_so=$(printf "\e[1;44;33m")
#export LESS_TERMCAP_ue=$(printf "\e[0m")
#export LESS_TERMCAP_us=$(printf "\e[1;32m")


## Shortcut Script for LF:
[ ! -f "$XDG_CONFIG_HOME/shell/shortcutrc" ] && setsid -f shortcuts >/dev/null 2>&1

# Startx for TTY (Xorg)
# [ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

# Start-DWL for TTY (Wayland)
#if [ "$(tty)" = "/dev/tty1" ]; then
#    exec "$HOME/.local/bin/start-dwl"
#fi

# Switch keys ESC and CAPS for TTY & no password
#sudo -n loadkeys "$XDG_DATA_HOME/larbs/ttymaps.kmap" 2>/dev/null
